version: '3'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    links:
      - redis

  uploader:
    build:
      context: ./upload_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"
    links:
      - mongodb

  redis:
    image: redis:alpine

  mongodb:
    image: mongo