version: '3'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    links:
      - redis

  redis:
    image: "redis:alpine"
